### ISSUE TITLE
Problem when resuming training

### ISSUE THREAD

**Issue by BeatWolf** [jpuigcerver/PyLaia#12]
When trying to continue an already started training (i finished a few epochs, evaluated the results and wanted to continue training), i got the following error:

`019-03-06 15:03:33,653 INFO laia.common.loader : Loaded checkpoint train/experiment.ckpt.lowest-valid-cer-12
Traceback (most recent call last):
  File "/data1/home/beat.wolf/anaconda3/envs/tf/bin/pylaia-htr-train-ctc", line 4, in <module>
    __import__('pkg_resources').run_script('laia==0.1.0', 'pylaia-htr-train-ctc')
  File "/data1/home/beat.wolf/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data1/home/beat.wolf/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/data1/home/beat.wolf/anaconda3/envs/tf/lib/python3.6/site-packages/laia-0.1.0-py3.6.egg/EGG-INFO/scripts/pylaia-htr-train-ctc", line 237, in <module>
    os.path.join(args.train_path, "experiment.{}".format(args.checkpoint))
  File "/data1/home/beat.wolf/anaconda3/envs/tf/lib/python3.6/site-packages/laia-0.1.0-py3.6.egg/laia/common/loader.py", line 138, in load_by
    pattern, key=key, reverse=reverse
  File "/data1/home/beat.wolf/anaconda3/envs/tf/lib/python3.6/site-packages/laia-0.1.0-py3.6.egg/laia/common/loader.py", line 98, in load_by
    return self.load(filepath)
  File "/data1/home/beat.wolf/anaconda3/envs/tf/lib/python3.6/site-packages/laia-0.1.0-py3.6.egg/laia/common/loader.py", line 132, in load
    set_rng_state(state.pop("rng"), self._device)
  File "/data1/home/beat.wolf/anaconda3/envs/tf/lib/python3.6/site-packages/laia-0.1.0-py3.6.egg/laia/common/random.py", line 32, in set_rng_state
    torch.set_rng_state(state["torch_cpu"])
  File "/data1/home/beat.wolf/anaconda3/envs/tf/lib/python3.6/site-packages/torch/random.py", line 14, in set_rng_state
    default_generator.set_state(new_state)
TypeError: expected a torch.ByteTensor, but got torch.cuda.ByteTensor`

**Comment by jpuigcerver** [comment]
Hi, PyLaia has not been properly launched yet, and the "master" branche is outdated.

If you want to use the latest version, please switch to the "refactor_kws_egs_master" branch. You can follow the example in egs/iam_htr. The rest of examples problably won't work, since I didn't have time to fix them yet.

**Comment by BeatWolf** [comment]
Thank you for your fast feedback. I was not aware that the mast branch is out of date and will from now on use the branch you mentioned.
