### ISSUE TITLE
bad tensor format

### ISSUE THREAD

**Issue by pedro-dreyer** [jpuigcerver/PyLaia#16]
I was trying to run the iam-htr example and I received the following error:

```
Train:   0%|          | 0/617 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/pylaia-htr-train-ctc", line 4, in <module>
    __import__('pkg_resources').run_script('laia==0.1.0', 'pylaia-htr-train-ctc')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/laia-0.1.0-py2.7.egg/EGG-INFO/scripts/pylaia-htr-train-ctc", line 279, in <module>
    experiment.run()
  File "/usr/local/lib/python2.7/dist-packages/laia-0.1.0-py2.7.egg/laia/experiments/experiment.py", line 76, in run
    self._tr_engine.run()
  File "/usr/local/lib/python2.7/dist-packages/laia-0.1.0-py2.7.egg/laia/hooks/action.py", line 31, in wrapper
    **{k: v for k, v in kwargs.items() if k in argspec.args}
  File "/usr/local/lib/python2.7/dist-packages/laia-0.1.0-py2.7.egg/laia/engine/trainer.py", line 126, in run
    self._run_epoch()
  File "/usr/local/lib/python2.7/dist-packages/laia-0.1.0-py2.7.egg/laia/engine/engine.py", line 224, in _run_epoch
    self._run_iteration(it, batch)
  File "/usr/local/lib/python2.7/dist-packages/laia-0.1.0-py2.7.egg/laia/engine/trainer.py", line 180, in _run_iteration
    batch_loss = self.compute_loss(batch, batch_output, batch_target)
  File "/usr/local/lib/python2.7/dist-packages/laia-0.1.0-py2.7.egg/laia/engine/trainer.py", line 228, in compute_loss
    return loss
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/laia-0.1.0-py2.7.egg/laia/engine/engine.py", line 240, in exception_catcher
    raise_from(wrapper, e)
  File "/usr/local/lib/python2.7/dist-packages/torch/_six.py", line 117, in raise_from
    raise value
laia.engine.engine_exception.EngineException: Exception "RuntimeError("Tensor for argument #2 'targets' is on CPU, but expected it to be on GPU (while checking arguments for ctc_loss_gpu)",)" raised during epoch 0, iteration 0. The batch that caused the exception was: ['b01-073-03', 'h04-007-04', 'g06-045m-05', 'b06-015-10', 'e01-050-03', 'f04-028-00', 'a01-038-09', 'c02-026-06', 'a01-128-04', 'a01-043-05']

```
Any ideas how to fix it?

Specs: Debian 9, Python 3.7

**Comment by jpuigcerver** [comment]
Hi,

I need to be able to reproduce the errors. Can you please paste the actual command line that you used to run the program?

**Comment by pedro-dreyer** [comment]
The error appears after I run the script `train_puigcerver17.sh;` in the `egs/iam-htr/src/` folder.

**Comment by jpuigcerver** [comment]
Hi,

This seems to be a problem with PyTorch 1.1.0. 

I can't find exactly where in the code, but it seems that torch.nn.functional.ctc_loss is called it checks that both log_probs and targets are in the same device.
On the other hand, cudnn's CTC implementation checks that targets is in the CPU.

I disabled cudnn for the computation of the ctc_loss, but it should be used in the rest of the code: See commit 41d2cc41d742e7ab336393fde8f56585ff49ee52
