### ISSUE TITLE
Error when runing IAM example

### ISSUE THREAD

**Issue by manucarbonell** [jpuigcerver/PyLaia#18]
Hi, I'm trying to run the iam-htr example but get this error when the training is about to start. Do you know what can be the reason?
````
Train:   0%|                                                                                                                                                                        | 0/617 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/mcarbonell/Documents/PyLaia/laia/engine/engine.py", line 232, in exception_catcher
    yield
  File "/home/mcarbonell/Documents/PyLaia/laia/engine/trainer.py", line 222, in compute_loss
    loss = self._criterion(batch_output, batch_target, **kwargs)
  File "/home/mcarbonell/virtualenvs/pylaia/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mcarbonell/Documents/PyLaia/laia/losses/ctc_loss.py", line 341, in forward
    acts, target, act_lens, valid_indices if err_indices else None
  File "/home/mcarbonell/Documents/PyLaia/laia/losses/ctc_loss.py", line 143, in forward
    device=torch.device("cpu"),
TypeError: an integer is required (got type NoneType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mcarbonell/Documents/PyLaia/egs/iam-htr/../../pylaia-htr-train-ctc", line 279, in <module>
    experiment.run()
  File "/home/mcarbonell/Documents/PyLaia/laia/experiments/experiment.py", line 76, in run
    self._tr_engine.run()
  File "/home/mcarbonell/Documents/PyLaia/laia/hooks/action.py", line 31, in wrapper
    **{k: v for k, v in kwargs.items() if k in argspec.args}
  File "/home/mcarbonell/Documents/PyLaia/laia/engine/trainer.py", line 126, in run
    self._run_epoch()
  File "/home/mcarbonell/Documents/PyLaia/laia/engine/engine.py", line 224, in _run_epoch
    self._run_iteration(it, batch)
  File "/home/mcarbonell/Documents/PyLaia/laia/engine/trainer.py", line 180, in _run_iteration
    batch_loss = self.compute_loss(batch, batch_output, batch_target)
  File "/home/mcarbonell/Documents/PyLaia/laia/engine/trainer.py", line 228, in compute_loss
    return loss
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mcarbonell/Documents/PyLaia/laia/engine/engine.py", line 240, in exception_catcher
    raise_from(wrapper, e)
  File "<string>", line 3, in raise_from
laia.engine.engine_exception.EngineException: Exception "TypeError('an integer is required (got type NoneType)',)" raised during epoch 0, iteration 0. The batch that caused the exception was: ['b03-092-03', 'c02-078-05', 'a03-040-01', 'r03-030-05', 'a04-003-03', 'f03-191-01', 'a02-120-08', 'e07-079-08', 'c06-076-07', 'g04-011-07']
Train:   0%|                                                                                                                                                                        | 0/617 [00:00<?, ?it/s]
```
`

**Comment by kleopatramarkou** [comment]
Hello, I have the same exact problem. Is there a solution ?

**Comment by jpuigcerver** [comment]
Which PyTorch version are you using?

**Comment by manucarbonell** [comment]
1.2.0

**Comment by jpuigcerver** [comment]
I'm looking into this. Unit tests pass for PyTorch 1.2.0 (https://travis-ci.com/jpuigcerver/PyLaia), so it's probably something not covered by them.

**Comment by jpuigcerver** [comment]
Hi, I'm still looking into this. I'm running the example with PyTorch 1.2.0 in my computer right now.

```bash
$ pip list | grep torch
nnutils-pytorch   0.5.0    
torch             1.2.0    
torchvision       0.4.0    
```

Could you paste the output of the previous command in your machines?

**Comment by kleopatramarkou** [comment]
$ pip list | grep torch
nnutils-pytorch   0.4.0    
torch             1.2.0+cu92   
torchvision       0.4.0+cu92

**Comment by jpuigcerver** [comment]
I believe that the problem is that some of the necessary files to run the experiments were not generated properly. 

In particular, check that the following files contain multiple lines:
- data/lang/puigcerver/lines/char/tr.txt
- exper/puigcerver17/train/syms_ctc.txt

**Comment by jpuigcerver** [comment]
I added a few checks in the IAM scripts to make sure that the required programs are installed (https://github.com/jpuigcerver/PyLaia/commit/fa1b5e73a00a8a84631f51d1c014ce91ccaf3137).

The safest option would be to delete the "data/lang" and "exper" directories and re-launch run.sh to make sure that all files are generated properly. Once you do this, the problem should be solved.

**Comment by manucarbonell** [comment]
Works, thank you
