### ISSUE TITLE
UserWarning: nnutils does not seem to be installed, masking cannot be used

### ISSUE THREAD

**Issue by Hunt3rM4d** [jpuigcerver/PyLaia#25]
Hello, after installing PyLaia using the small script you provide in an Ubuntu 20.04 machine with a Python 3.7 virtual environment and trying to run some experiments the following error appears:

/home/dvillanova/tfgenv/lib/python3.7/site-packages/laia-0.1.0-py3.7.egg/laia/models/htr/conv_block.py:56: UserWarning: nnutils does not seem to be installed, masking cannot be used
  "nnutils does not seem to be installed, masking cannot be used"
Traceback (most recent call last):
  File "/home/dvillanova/tfgenv/bin/pylaia-htr-create-model", line 4, in <module>
    __import__('pkg_resources').run_script('laia==0.1.0', 'pylaia-htr-create-model')
  File "/home/dvillanova/tfgenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dvillanova/tfgenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/home/dvillanova/tfgenv/lib/python3.7/site-packages/laia-0.1.0-py3.7.egg/EGG-INFO/scripts/pylaia-htr-create-model", line 223, in <module>
    model = LaiaCRNN(**parameters)
  File "/home/dvillanova/tfgenv/lib/python3.7/site-packages/laia-0.1.0-py3.7.egg/laia/models/htr/laia_crnn.py", line 75, in __init__
    sequencer=image_sequencer, columnwise=not vertical_text
  File "/home/dvillanova/tfgenv/lib/python3.7/site-packages/laia-0.1.0-py3.7.egg/laia/nn/image_pooling_sequencer.py", line 31, in __init__
    raise ImportError("nnutils does not seem installed")
ImportError: nnutils does not seem installed

And it does not make much sense as nnutils-pytorch was specifically installed as it is present in the requirements.txt file you provide. Do you have any insight regarding what could be missing?

**Comment by jpuigcerver** [comment]
Can you show the output of: ```python3 -m pip list | grep nnutils```?

**Comment by Hunt3rM4d** [comment]
Sure thing. The output is:
nnutils-pytorch 0.6.0.post1

**Comment by jpuigcerver** [comment]
I don't know what's exactly the root of your problem, but I have updated nnutils-pytorch to support PyTorch 1.5.0, and PyLaia works now with this version as well (I tested GPU on my computer and CPU on Travis).

I'm closing this issue, but let me know if you have any issue.

**Comment by jkloe** [comment]
pytorch==1.6.0 does not seem to be compatible with nnutils, so this error appears again. Using pytorch==1.5.0 and torchvision==0.6.0 does work however.
