### ISSUE TITLE
Error about missing symbols in the symbols table

### ISSUE THREAD

**Issue by JediKnightChan** [jpuigcerver/PyLaia#37]
Hi, maybe I don't completely understand the structure for the required files, but I tried to guess them looking at the code.

Command I use is 
`./laia/scripts/htr/train_ctc.py syms.txt [./train_rus2/images/] tr.txt val.txt`

Where
./train_rus2/images/ contains jpg files with names such as 00000003_1.jpg, etc

tr.txt and val.txt contain strings like that:
00000003_1 въ доме московскаго универ
00000003_10 валентина
(\<image filename without .jpg\> \<string that corresponds to the image\>)

Where syms.txt contains
```
⊗ 0
) 1
+ 2
/ 3
0 4
1 5
2 6
3 7
4 8
5 9
6 10
7 11
8 12
9 13
[ 14
] 15
i 16
k 17
l 18
| 19
× 20
ǂ 21
а 22
б 23
в 24
г 25
д 26
е 27
ж 28
з 29
и 30
й 31
к 32
л 33
м 34
н 35
о 36
п 37
р 38
с 39
т 40
у 41
ф 42
х 43
ц 44
ч 45
ш 46
щ 47
ъ 48
ы 49
ь 50
э 51
ю 52
я 53
і 54
– 55
. 56
<space> 57
```
What I get is 
```
[2021-03-03 16:08:03, ... ERROR laia.data.transforms.text.transforms] Could not find ... in the symbols table
[2021-03-03 16:08:03,856 ERROR laia.data.transforms.text.transforms] Could not find "20" in the symbols table
[2021-03-03 16:08:04,049 CRITICAL laia] Uncaught exception:
Traceback (most recent call last):
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_exception.py", line 27, in exception_catcher
    yield
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_module.py", line 115, in compute_loss
    batch_loss = self.criterion(batch_y_hat, batch_y, **kwargs)
  File "/home/pchela/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pchela/TextRecognition/PyLaia/laia/losses/ctc_loss.py", line 102, in forward
    y = torch.tensor(list(itertools.chain.from_iterable(y)), dtype=torch.int)
TypeError: an integer is required (got type NoneType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./laia/scripts/htr/train_ctc.py", line 204, in <module>
    main()
  File "./laia/scripts/htr/train_ctc.py", line 200, in main
    run(**args)
  File "./laia/scripts/htr/train_ctc.py", line 128, in run
    trainer.fit(engine_module, datamodule=data_module)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 468, in fit
    results = self.accelerator_backend.train()
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 61, in train
    results = self.train_or_test()
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 490, in train
    self.run_sanity_check(self.get_model())
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 697, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 613, in run_evaluation
    output = self.evaluation_loop.evaluation_step(test_mode, batch, batch_idx, dataloader_idx)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 178, in evaluation_step
    output = self.trainer.accelerator_backend.validation_step(args)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 77, in validation_step
    output = self.trainer.model.validation_step(*args)
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/htr_engine_module.py", line 72, in validation_step
    result = super().validation_step(batch, *args, **kwargs)
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_module.py", line 150, in validation_step
    batch_loss = self.compute_loss(batch, batch_y_hat, batch_y)
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_module.py", line 119, in compute_loss
    return batch_loss
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_exception.py", line 29, in exception_catcher
    raise EngineException(
laia.engine.engine_exception.EngineException: Exception "TypeError('an integer is required (got type NoneType)')" raised during epoch=0, global_step=0 with batch=['00000004_20', '00000003_22', '00000003_8', '00000004_34', '00000003_5', '00000003_36', '00000004_48', '00000003_0']`
```

**Comment by carmocca** [comment]
It's probably because you are missing the CTC symbol

`<ctc> 0`

Try putting it in your `syms.txt` file

**Comment by carmocca** [comment]
Also notice the two errors at the top

```
[2021-03-03 16:08:03, ... ERROR laia.data.transforms.text.transforms] Could not find ... in the symbols table
[2021-03-03 16:08:03,856 ERROR laia.data.transforms.text.transforms] Could not find "20" in the symbols table
```

Which means either you didn't add them to `syms.txt` or there is an issue in your tokenization

**Comment by JediKnightChan** [comment]
I replaced "⊗ 0" with "<ctc> 0" in the syms.txt file. However, the problem still persists.

Yeah, this script is looking for strings of text (which correspond to the images) in syms.txt for some reason (probably because letters are Cyrillic). Is there a way to fix it? 

It is also suspicious that batch contains image string ids instead of image tensors.

**Comment by JediKnightChan** [comment]
It's also a pity I can't see how exactly the dataset is organized in the IAM dataset, because of this error:
```
2021-03-05 13:54:24 (501 MB/s) - ‘data/original/words.tgz’ saved [4720/4720]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Failed extracting IAM ascii files.

```

**Comment by carmocca** [comment]
> I replaced "⊗ 0" with " 0" in the syms.txt file. However, the problem still persists.

I'm saying it should be

```python
<ctc> 0
⊗ 1
) 2
+ 3
/ 4
```

> Yeah, this script is looking for strings of text (which correspond to the images) in syms.txt for some reason (probably because letters are Cyrillic). Is there a way to fix it?

Is your text properly tokenized? as in, every token is present in the `syms.txt` file?

> It is also suspicious that batch contains image string ids instead of image tensors.

That's on purpose so it's easy to see which images produced an exception, as sometimes the failure comes due to images being too small or not correctly labeled

> because of this error:

What did you run that produced this error?

You can try running a benchmark to see the general structure

https://github.com/jpuigcerver/PyLaia/blob/master/benchmarks

**Comment by JediKnightChan** [comment]
> I'm saying it should be
> 
> ```python
> <ctc> 0
> ⊗ 1
> ) 2
> + 3
> / 4
> ...
> ```

Yeah, sorry, I meant that, but forgot about Markdown escape symbols.

> Is your text properly tokenized? as in, every token is present in the `syms.txt` file?

I thought only letters and other chars should be in syms.txt, because Handwritten recognition recongnizes them in the CTCLoss neural networks. Does it require words?

> What did you run that produced this error?

I ran run.sh from https://github.com/carmocca/PyLaia-examples/tree/master/iam-htr

**Comment by carmocca** [comment]
> I thought only letters and other chars should be in syms.txt, because Handwritten recognition recongnizes them in the CTCLoss neural networks. Does it require words or strings?

So if your image contains `The red house` with id `img-01.jpg`

You'd have the line text:

`img-01 T h e <space> r e d <space> h o u s e`

and your `syms.txt`

```
<ctc> 0
T 1
h 2
e 3
r 4
d 5
h 6
o 7
u 8
s 9
<space> 10
```

> I ran run.sh from https://github.com/carmocca/PyLaia-examples/tree/master/iam-htr I specified correct username and password, and I already encountered problems downloading and extracting words.tgz before.


Unfortunately, I don't have crendentials to test it, but if you have the local files, you can adapt https://github.com/carmocca/PyLaia-examples/blob/master/iam-htr/src/download.sh to skip the actual download part.

**Comment by JediKnightChan** [comment]
Thanks, now I see that strings of text should contain \<space\> instead of spaces, which are used here as char separators. That solved the error, but I got another one: 'The loss is NaN or ± inf', that seems not connected with the previous error, so I'll close this issue and open another
