### ISSUE TITLE
The loss is NaN or ± inf

### ISSUE THREAD

**Issue by JediKnightChan** [jpuigcerver/PyLaia#38]
While training the model, I got the following error:
```
(pyl2) pchela@main-computational-machine-2:~/TextRecognition/PyLaia$ ./laia/scripts/htr/train_ctc.py syms.txt [./train_rus2/images/] tr.txt val.txt 

[2021-03-06 09:50:40,183 INFO laia] Arguments: {'syms': 'syms.txt', 'img_dirs': ['./train_rus2/images/'], 'tr_txt_table': 'tr.txt', 'va_txt_table': 'val.txt', 'common': CommonArgs(seed=74565, train_path='', model_filename='model', experiment_dirname='experiment', monitor=<Monitor.va_cer: 'va_cer'>, checkpoint=None), 'data': DataArgs(batch_size=8, color_mode=<ColorMode.L: 'L'>), 'train': TrainArgs(delimiters=['<space>'], checkpoint_k=3, resume=False, early_stopping_patience=20, gpu_stats=False, augment_training=False), 'optimizer': OptimizerArgs(name=<Name.RMSProp: 'RMSProp'>, learning_rate=0.0005, momentum=0.0, weight_l2_penalty=0.0, nesterov=False), 'scheduler': SchedulerArgs(active=False, monitor=<Monitor.va_loss: 'va_loss'>, patience=5, factor=0.1), 'trainer': TrainerArgs(gradient_clip_val=0, process_position=0, num_nodes=1, num_processes=1, gpus=None, auto_select_gpus=False, tpu_cores=None, progress_bar_refresh_rate=1, overfit_batches=0.0, track_grad_norm=-1, check_val_every_n_epoch=1, fast_dev_run=False, accumulate_grad_batches=1, max_epochs=1000, min_epochs=1, max_steps=None, min_steps=None, limit_train_batches=1.0, limit_val_batches=1.0, limit_test_batches=1.0, val_check_interval=1.0, flush_logs_every_n_steps=100, log_every_n_steps=50, accelerator=None, sync_batchnorm=False, precision=32, weights_summary='top', weights_save_path=None, num_sanity_val_steps=2, truncated_bptt_steps=None, profiler=None, benchmark=False, deterministic=False, reload_dataloaders_every_epoch=False, replace_sampler_ddp=True, terminate_on_nan=False, prepare_data_per_node=True, plugins=None, amp_backend='native', amp_level='O2', distributed_backend=None, automatic_optimization=None, move_metrics_to_cpu=False, enable_pl_optimizer=True)}

[2021-03-06 09:50:41,546 INFO laia] Installed:
[2021-03-06 09:50:41,605 INFO laia.common.loader] Loaded model model
[2021-03-06 09:50:41,606 INFO laia.engine.data_module] Training data transforms:
ToImageTensor(
  vision.Convert(mode=L),
  vision.Invert(),
  ToTensor()
)
[2021-03-06 09:50:41,656 INFO lightning] GPU available: True, used: False
[2021-03-06 09:50:41,656 INFO lightning] TPU available: False, using: 0 TPU cores
[2021-03-06 09:50:41,657 WARNING py.warnings] UserWarning: GPU available but not used. Set the --gpus flag when calling the script.
[2021-03-06 09:50:41,678 INFO lightning]
  | Name      | Type     | Params
---------------------------------------
0 | model     | LaiaCRNN | 4.8 M
1 | criterion | CTCLoss  | 0
---------------------------------------
4.8 M     Trainable params
0         Non-trainable params
4.8 M     Total params

[2021-03-06 09:50:42,408 INFO laia] VA sanity check: 100% 2/2 [00:00<00:00, 2.91it/s]
[2021-03-06 09:50:46,026 CRITICAL laia] Uncaught exception:
Traceback (most recent call last):
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_exception.py", line 27, in exception_catcher
    yield
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_module.py", line 118, in compute_loss
    raise ValueError("The loss is NaN or ± inf")
ValueError: The loss is NaN or ± inf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./laia/scripts/htr/train_ctc.py", line 204, in <module>
    main()
  File "./laia/scripts/htr/train_ctc.py", line 200, in main
    run(**args)
  File "./laia/scripts/htr/train_ctc.py", line 128, in run
    trainer.fit(engine_module, datamodule=data_module)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 468, in fit
    results = self.accelerator_backend.train()
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 61, in train
    results = self.train_or_test()
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 521, in train
    self.train_loop.run_training_epoch()
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 546, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 698, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 480, in optimizer_step
    optimizer.step(closure=train_step_and_backward_closure)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 226, in step
    optimizer.step(closure=closure, *args, **kwargs)
  File "/home/pchela/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/pchela/.local/lib/python3.8/site-packages/torch/optim/rmsprop.py", line 66, in step
    loss = closure()
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 688, in train_step_and_backward_closure
    result = self.training_step_and_backward(
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 778, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 327, in training_step
    training_step_output = self.trainer.accelerator_backend.training_step(args)
  File "/home/pchela/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 69, in training_step
    output = self.trainer.model.training_step(*args)
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/htr_engine_module.py", line 37, in training_step
    result = super().training_step(batch, *args, **kwargs)
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_module.py", line 132, in training_step
    batch_loss = self.compute_loss(batch, batch_y_hat, batch_y)
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_module.py", line 119, in compute_loss
    return batch_loss
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pchela/TextRecognition/PyLaia/laia/engine/engine_exception.py", line 29, in exception_catcher
    raise EngineException(
laia.engine.engine_exception.EngineException: Exception "ValueError('The loss is NaN or ± inf')" raised during epoch=0, global_step=3 with batch=['/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_37.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_35.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_39.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_33.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_4.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_34.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_32.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_38.jpg']
```

No erorrs about missing tokens in syms.txt here

**Comment by carmocca** [comment]
Can you check that those images are properly annotated?

`['/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_37.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_35.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_39.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_33.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_4.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_34.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_32.jpg', '/home/pchela/TextRecognition/PyLaia/train_rus2/images/00000003_38.jpg']`

And can you re-run with `--logging.level DEBUG`?

**Comment by JediKnightChan** [comment]
This issue was caused by using the model created using another version of syms.txt. After rerunning ./laia/scripts/htr/create_model.py the problem was solved

**Comment by SanaNGU** [comment]
@JediKnightChan thank you very much , i had the same issue then I recreated the model. Thank you
