### ISSUE TITLE
Support for PyTorch 1.8.1 (or PyTorch > 1.7.0 in general)

### ISSUE THREAD

**Issue by jkloe** [jpuigcerver/PyLaia#39]
When I install PyTorch 1.8.1 with CUDA 11.1 support (from https://pytorch.org/get-started/locally: `pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`), I get the following error when running e.g. `pylaia-htr-decode-ctc`:
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (torch 1.8.1+cu111 (/usr/local/anaconda3/lib/python3.8/site-packages), Requirement.parse('torch<1.7.0,>=1.6.0'), {'nnutils-pytorch'})
```
Seems to be that `nnutils-pytorch` does not support torch > 1.7.0?

**Comment by jkloe** [comment]
I have now successfully compiled nnutils-pytorch for the above configuration and all seems to work fine.

**Comment by carmocca** [comment]
> Seems to be that nnutils-pytorch does not support torch > 1.7.0?

It should, it's just that there is not maintenance currently 😕 

I opened https://github.com/jpuigcerver/nnutils/pull/5 to update this a bit ago. Would need to come back to it and ping Joan to merge.

> I have now successfully compiled nnutils-pytorch for the above configuration and all seems to work fine.

I'm glad you could work around it though

**Comment by dstoekl** [comment]
installation fails on nnutils-pytorch. @jkloe how did you manage to compile it?

**Comment by jkloe** [comment]
@dstoekl after installing the pytorch version I needed (`pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`), I did a manual compilation of nnutils-pytorch - I had to change the `pytorch/requirements.txt` file there (removed the version restrictions of the `torch` library) and also `pytorch/setup.py`, where I changed the version number to 1.8.1 (corresponding to the version of pytorch).  Then `python setup.py build && python setup.py install` worked for me.

**Comment by dstoekl** [comment]
excellent! many thanks for your indications @jkloe

**Comment by jjsr** [comment]
HI I am still getting the error , may be i have missed something may you please explain again what we need to do to make code working I am getting nnutlis error
